//! # Problem 2: Even Fibonacci Numbers
//!
//! **Difficulty:** ⭐
//! **Link:** <https://projecteuler.net/problem=2>
//!
//! ## Problem Statement
//!
//! Each new term in the Fibonacci sequence is generated by adding the previous
//! two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not
//! exceed four million, find the sum of the even-valued terms.
//!
//! ## Mathematical Solution
//!
//! TODO
//!
//! ## Complexity
//!
//! - Time: $O(?)$
//! - Space: $O(?)$
//!
//! ## Example
//!
//! ```rust
//! # fn solve(limit: u64) -> u64 {
//! #     todo!()
//! # }
//! // Even Fibonacci terms below 10: 2, 8 → sum = 10
//! assert_eq!(solve(10), 10);
//! ```

/// Solve Problem 2
fn solve(limit: u64) -> u64 {
    todo!()
}

fn main() {
    let answer = solve(4_000_000);
    println!("{}", answer);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example() {
        // Even Fibonacci terms below 10: 2, 8 → sum = 10
        assert_eq!(solve(10), 10);
    }

    #[test]
    fn test_answer() {
        assert_eq!(solve(4_000_000), 4613732);
    }
}
