//! # Problem 2: Even Fibonacci Numbers
//!
//! **Difficulty:** ⭐
//! **Link:** <https://projecteuler.net/problem=2>
//!
//! ## Problem Statement
//!
//! Each new term in the Fibonacci sequence is generated by adding the previous
//! two terms. By starting with 1 and 2, the first 10 terms will be:
//!
//! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//!
//! By considering the terms in the Fibonacci sequence whose values do not
//! exceed four million, find the sum of the even-valued terms.
//!
//! ## Mathematical Solution
//!
//! The Fibonacci sequence has a repeating parity pattern: odd, odd, even, odd, odd, even, ...
//! So every 3rd term is even. The even-indexed Fibonacci numbers satisfy their own recurrence:
//!
//! $$E_n = 4 E_{n-1} + E_{n-2}, \quad E_1 = 2,\ E_2 = 8$$
//!
//! This lets us iterate only over even Fibonacci numbers directly, skipping 2/3 of the work.
//!
//! ## Complexity
//!
//! - `solve2` (brute force): Time $O(\log \text{limit})$, Space $O(1)$
//! - `solve`  (math):        Time $O(\log \text{limit})$, Space $O(1)$, ~3× fewer iterations

#[allow(dead_code)]
fn solve2(limit: u64) -> u64 {
    let (mut a, mut b) = (1u64, 2u64);
    let mut sum = 0;
    while a <= limit {
        if a % 2 == 0 {
            sum += a;
        }
        (a, b) = (b, a + b);
    }
    sum
}

fn solve(limit: u64) -> u64 {
    let (mut a, mut b) = (2u64, 8u64);
    let mut sum = 0;
    while a <= limit {
        sum += a;
        (a, b) = (b, 4 * b + a);
    }
    sum
}

fn main() {
    let answer = solve(4_000_000);
    println!("{}", answer);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example() {
        assert_eq!(solve(10), 10);
        assert_eq!(solve2(10), 10);
    }

    #[test]
    fn test_answer() {
        assert_eq!(solve(4_000_000), 4613732);
        assert_eq!(solve2(4_000_000), 4613732);
    }
}
