//! # Problem 12: Highly Divisible Triangular Number
//!
//! **Difficulty:** ⭐⭐
//! **Link:** <https://projecteuler.net/problem=12>
//!
//! ## Problem Statement
//!
//! The sequence of triangle numbers is generated by adding the natural numbers:
//! 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//!
//! The 7th triangle number, 28, has six divisors: 1, 2, 4, 7, 14, 28.
//!
//! What is the value of the first triangle number to have over five hundred divisors?
//!
//! ## Mathematical Solution
//!
//! TODO

fn solve() -> u64 {
    //平方根算法
    
    0
}

fn main() {
    println!("{}", solve());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_example() {
        // 28 is the first triangle number with more than 5 divisors
        assert_eq!(solve(), 0); // TODO: fill in answer
    }
}
